### ISSUE TITLE
Как получить токен по логину и паролю?

### ISSUE THREAD

**Issue by nickmetal** [Hixon10/simple-rest-yandex-disk-client#2]
В файле example.py:

`class ExamplesOfUsingOfYandexDiskRestClient:`
    `..def __init__(self):`
    `....token = "ea191c8546be4149a6319d9959328831"`
    `....self.client = YandexDiskRestClient(token)`

как осуществить запрос на яндекс для получение этого токена?  Чтобы его не хардкодить

**Comment by Hixon10** [comment]
https://tech.yandex.ru/oauth/ - тут всё есть про это. В моём случае я, кажется, просто взял девелоперский ключ.

**Comment by Frodox** [comment]
Нужно регистрировать своё приложение. иначе никак, похоже
